"""Initial migration

Revision ID: 47b64f9d305c
Revises: 
Create Date: 2025-12-28 01:50:04.017577+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47b64f9d305c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holdings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('average_cost', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('current_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('invested_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('unrealized_pl', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('realized_pl', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('xirr', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('asset_class', sa.String(length=20), nullable=True),
    sa.Column('strategy', sa.String(length=20), nullable=True),
    sa.Column('market', sa.String(length=10), nullable=True),
    sa.Column('first_purchase_date', sa.Date(), nullable=True),
    sa.Column('last_transaction_date', sa.Date(), nullable=True),
    sa.Column('holding_days', sa.Integer(), nullable=True),
    sa.Column('is_price_auto_updated', sa.Boolean(), nullable=True),
    sa.Column('last_calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'symbol', name='uq_portfolio_symbol')
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('amount_jpy', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('asset_class', sa.String(length=20), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transaction_date', 'transactions', ['transaction_date'], unique=False)
    op.create_index('idx_transaction_portfolio_symbol', 'transactions', ['portfolio_id', 'symbol'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=True),
    sa.Column('holding_id', sa.UUID(), nullable=True),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('prediction_data', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('forecast_horizon_days', sa.Integer(), nullable=True),
    sa.Column('predicted_for_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['holding_id'], ['holdings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_holding_predictions', 'predictions', ['holding_id'], unique=False)
    op.create_index('idx_portfolio_predictions', 'predictions', ['portfolio_id', 'model_type'], unique=False)
    op.create_index('idx_predictions_unexpired', 'predictions', ['portfolio_id', 'model_type', 'expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_predictions_unexpired', table_name='predictions')
    op.drop_index('idx_portfolio_predictions', table_name='predictions')
    op.drop_index('idx_holding_predictions', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index('idx_transaction_portfolio_symbol', table_name='transactions')
    op.drop_index('idx_transaction_date', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('holdings')
    op.drop_table('portfolios')
    # ### end Alembic commands ###
